//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars411.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Level
    {
        public int Access_ID { get; set; }
        public string Access_Level_Type { get; set; }
        public Nullable<int> UID { get; set; }
    }
}
