//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars411.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Level_Menu
    {
        public int ID { get; set; }
        public Nullable<int> Access_ID { get; set; }
        public Nullable<int> Page_ID { get; set; }
    }
}
