//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars411.Models
{
    using System;
    
    public partial class getBestCarRating_Result2
    {
        public int PostID { get; set; }
        public string PostDescription { get; set; }
        public string PostImage { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string PostTitle { get; set; }
        public Nullable<decimal> Relaiability { get; set; }
        public Nullable<decimal> Safety { get; set; }
        public Nullable<decimal> Comfort { get; set; }
        public Nullable<decimal> Aveg { get; set; }
    }
}
