//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars411.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        public int BlogID { get; set; }
        public string Blogtitle { get; set; }
        public string Description { get; set; }
        public string BlogImage { get; set; }
        public string BlogType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
