//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars411.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int CommentID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> IsParent { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> Relaiability { get; set; }
        public Nullable<int> Safety { get; set; }
        public Nullable<int> Comfort { get; set; }
        public Nullable<int> PostID { get; set; }
        public string UserName { get; set; }
        public string UserImage { get; set; }
        public string UserType { get; set; }
    }
}
