//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars411.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int User_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email_Adress { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> LicenseExpiry { get; set; }
        public Nullable<System.DateTime> ServiceExpiry { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int Access_Level_ID { get; set; }
        public string ImagePath { get; set; }
        public string UserType { get; set; }
    }
}
